table DimDate
	lineageTag: 59d6bfd3-92eb-461f-9490-b8f4ade6556e

	column DateKey
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: int
		lineageTag: 916fdd34-9bf6-4a5a-aa16-0a9fd899633e
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column DayNumberOfWeek
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: tinyint
		lineageTag: 3171de6a-b665-4875-b439-c7472d68a79e
		summarizeBy: none
		sourceColumn: DayNumberOfWeek

		annotation SummarizationSetBy = Automatic

	column EnglishDayNameOfWeek
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(10)
		lineageTag: 989b26cb-a13f-4796-aba3-ebb3e3c8d3bd
		summarizeBy: none
		sourceColumn: EnglishDayNameOfWeek

		annotation SummarizationSetBy = Automatic

	column DayNumberOfMonth
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: tinyint
		lineageTag: 68cdce33-fe57-46f3-8f8b-9ed4ebe53240
		summarizeBy: none
		sourceColumn: DayNumberOfMonth

		annotation SummarizationSetBy = Automatic

	column DayNumberOfYear
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: smallint
		lineageTag: 0412b12d-ffd1-4172-ad1f-b7776b64a293
		summarizeBy: none
		sourceColumn: DayNumberOfYear

		annotation SummarizationSetBy = Automatic

	column WeekNumberOfYear
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: tinyint
		lineageTag: f8733be4-e596-4cd9-9b19-2f92afa11749
		summarizeBy: none
		sourceColumn: WeekNumberOfYear

		annotation SummarizationSetBy = Automatic

	column EnglishMonthName
		dataType: string
		isNullable: false
		sourceProviderType: nvarchar(10)
		lineageTag: 112f2ddd-d9d8-4bc2-a218-ab2ad2f3e24e
		summarizeBy: none
		sourceColumn: EnglishMonthName
		sortByColumn: MonthNumberOfYear

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column MonthNumberOfYear
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: tinyint
		lineageTag: 0dbc3546-9ddc-4e04-84d7-7b0ea1fc83cb
		summarizeBy: none
		sourceColumn: MonthNumberOfYear

		annotation SummarizationSetBy = Automatic

	column CalendarQuarter
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: tinyint
		lineageTag: 97fc4b5a-1f83-4450-9b97-f9fef5d917da
		summarizeBy: none
		sourceColumn: CalendarQuarter

		annotation SummarizationSetBy = Automatic

	column CalendarYear
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: smallint
		lineageTag: 4172c5a0-6bbe-4a99-a2e0-8cb541f764ec
		summarizeBy: none
		sourceColumn: CalendarYear

		annotation SummarizationSetBy = Automatic

	column CalendarSemester
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: tinyint
		lineageTag: ee655647-806d-447c-b613-4dbafcbcd3ee
		summarizeBy: none
		sourceColumn: CalendarSemester

		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: directQuery
		source =
				let
				    Source = Sql.Databases("localhost\SQLEXPRESS"),
				    AdventureWorksDW2022 = Source{[Name="AdventureWorksDW2022"]}[Data],
				    dbo_DimDate = AdventureWorksDW2022{[Schema="dbo",Item="DimDate"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_DimDate,{"DateKey", "DayNumberOfWeek", "EnglishDayNameOfWeek", "DayNumberOfMonth", "DayNumberOfYear", "WeekNumberOfYear", "EnglishMonthName", "MonthNumberOfYear", "CalendarQuarter", "CalendarYear", "CalendarSemester"}),
				    #"Extracted First Characters" = Table.TransformColumns(#"Removed Other Columns", {{"EnglishDayNameOfWeek", each Text.Start(_, 3), type text}}),
				    #"Extracted First Characters1" = Table.TransformColumns(#"Extracted First Characters", {{"EnglishMonthName", each Text.Start(_, 3), type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Extracted First Characters1", each [CalendarYear] >= 2010)
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

